README.adoc, finish/kubernetes.yaml, finish/name/src/main/webapp/WEB-INF/web.xml, finish/name/src/test/java/it/io/openliberty/guides/name/NameEndpointTest.java, finish/ping/src/main/webapp/WEB-INF/web.xml, finish/ping/src/test/java/it/io/openliberty/guides/ping/PingEndpointTest.java, start/name/src/main/webapp/WEB-INF/web.xml, start/name/src/test/java/it/io/openliberty/guides/name/NameEndpointTest.java, start/ping/src/main/webapp/WEB-INF/web.xml, start/ping/src/test/java/it/io/openliberty/guides/ping/PingEndpointTest.java
Minor text changes and add prerequesites section.
=> Incorporate feedback from #1

README.adoc
* Change title
* Add `kubectl get pods` command
* Remove "the pod's required resources"
=> Apply feedback from #7

finish/name/src/main/java/io/openliberty/guides/name/NameResource.java, finish/name/src/test/java/it/io/openliberty/guides/name/NameEndpointTest.java, finish/ping/src/main/java/io/openliberty/guides/ping/PingResource.java, finish/ping/src/test/java/it/io/openliberty/guides/ping/PingEndpointTest.java, start/name/src/main/java/io/openliberty/guides/name/NameResource.java, start/name/src/test/java/it/io/openliberty/guides/name/NameEndpointTest.java, start/ping/src/main/java/io/openliberty/guides/ping/PingResource.java, start/ping/src/test/java/it/io/openliberty/guides/ping/PingEndpointTest.java
@gkwan-ibm brought up some concerns while reviewing the Kube intro guide, I am incorporating the same feedback into this guide.
=> Incorporate pre-publish feedback from the Kube intro guide

.travis.yml
Setup minikube, create configmap and secret, run tests.
=> Update .travis.yml to setup minikube and run tests

README.adoc
Apply feedback from #12 
* Incorporate feedback for what you'll learn section
* Incorporate feedback for deploy name and ping applications section
* Incorporate feedback for create configmap and secret section
* Incorporate feedback for update kube resources section
* Incorporate feedback for deploy your changes section
* Incorporate feedback for testing the microservices section
* Incorporate feedback for teardown section
* Use 'with' instead of 'using' sometimes
* Change colons to periods
=> Apply ID review feedback from #12

README.adoc
=> Add specific instructions for getting the hostname

README.adoc
Update 'docker' to be 'Docker'.
=> Change 'docker' to 'Docker'

README.adoc
Applied the revisions pointed out in the commit.
=> Apply ID feedback

start/ping/src/main/java/io/openliberty/guides/ping/PingResource.java
Remove unused imports from ping resource.
=> Remove unused imports

README.adoc
Update SEO title and description to cover what we need and be more accurate.
=> Update SEO title and description

README.adoc
https://github.com/OpenLiberty/guides-common/pull/201
=> Add instructions to teardown minikube

.travis.yml
https://github.com/OpenLiberty/guide-kubernetes-microprofile-health/issues/28
=> Silent maven and wget output in travis

.travis.yml, scripts/travisTest.sh
- added travis test script for continuous dev build test
=> Added travis test script

README.adoc
=> Remove misleading hotspots

scripts/travisTest.sh
* Added set error flags to report intermediate cmd failure
* Removed empty space
=> Added set error flag to report intermediate cmd failure (#50)

README.adoc
Address feedback in #56 and ran acrolinx
=> Address Review Feedback

README.adoc
=> Address PR feedback

finish/inventory/pom.xml, finish/pom.xml, finish/system/pom.xml, start/inventory/pom.xml, start/pom.xml, start/system/pom.xml
Reduce the SRVE9967W warnings from the messages.log
#64 #65
=> Merge qa to master: Updating Dependencies

README.adoc
Issue:
OpenLiberty/guides-common#284
=> Fix capitalization for platform names

README.adoc
=> Merge qa to master: Fix capitalization for platform names

README.adoc
=> Qa to master:   Fix typo in page-description

finish/inventory/src/main/java/io/openliberty/guides/inventory/model/SystemData.java, start/inventory/src/main/java/io/openliberty/guides/inventory/model/SystemData.java
Issue: https://github.com/openliberty/guides-common/issues/301
=> fixed licensing for SystemData.java

README.adoc, finish/inventory/Dockerfile, finish/inventory/pom.xml, finish/inventory/src/main/liberty/config/server.xml, finish/pom.xml, finish/system/Dockerfile, finish/system/pom.xml, scripts/travisTest.sh, start/inventory/Dockerfile, start/inventory/pom.xml, start/inventory/src/main/liberty/config/server.xml, start/pom.xml, start/system/Dockerfile, start/system/pom.xml
=> Merge qa to master: docker content and mp3 updates

README.adoc, finish/inventory/pom.xml, finish/inventory/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java, finish/pom.xml, finish/system/pom.xml, finish/system/src/main/java/io/openliberty/guides/system/SystemResource.java, start/inventory/pom.xml, start/pom.xml, start/system/pom.xml
=> Merge qa to master: update hotspots and artifactId

README.adoc, scripts/travisTest.sh
Addressing issues:
- remove dockerfile.skip: https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/issues/84
- add curl: https://github.com/OpenLiberty/guide-kubernetes-microprofile-config/issues/83
=> add curl availability

README.adoc
=> Merge qa to master: add back a backtick

finish/inventory/pom.xml, finish/system/pom.xml, start/inventory/pom.xml, start/system/pom.xml
=> Merge qa to master: specify version directly in plugins

finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java, start/inventory/src/main/java/io/openliberty/guides/inventory/InventoryResource.java, start/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java
Made changes to error messages as part of https://github.com/OpenLiberty/guides-common/issues/243
=> Made error message changes

scripts/travisTest.sh
=> Merge qa to master: fix test failure in docker daily build automation test

CONTRIBUTING.md, README.adoc
PR: #110 
Issue: https://github.com/openliberty/guides-common/issues/514
=> Merge qa to master: add cd start command

.github/workflows/test.yml
- enable test for master branch
- skip test if only update README.adoc
=> Merge qa to master: Update test.yml (#118)

.github/workflows/test.yml, finish/inventory/pom.xml, finish/system/pom.xml, scripts/dailyBuild.sh, scripts/dockerImageTest.sh, scripts/startMinikube.sh, scripts/stopMinikube.sh, scripts/testApp.sh, start/inventory/pom.xml, start/system/pom.xml
=> Merge qa to master: add daily build GH action

.github/workflows/test.yml
=> Merge qa to master: enable pr checker

README.adoc, finish/inventory/pom.xml, finish/inventory/src/main/java/io/openliberty/guides/inventory/client/SystemClient.java, finish/inventory/src/main/liberty/config/server.xml, finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java, finish/kubernetes.yaml, finish/system/pom.xml, finish/system/src/main/java/io/openliberty/guides/system/SystemResource.java, finish/system/src/main/liberty/config/server.xml, finish/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java, scripts/startMinikube.sh, scripts/stopMinikube.sh, scripts/testApp.sh, start/inventory/pom.xml, start/inventory/src/main/liberty/config/server.xml, start/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java, start/system/pom.xml, start/system/src/main/java/io/openliberty/guides/system/SystemResource.java, start/system/src/main/liberty/config/server.xml, start/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java
* changed to configure context root
* readme updates
* minor test update
* fixed issue with inventory
* removed sys name from test command
* updated test section
* fixes to travis script
* fixed line spacing
* updated lisences
* changed test command
* travis test updates
* hardcoded context root in start
* fixed readme test output
* addressing windows peer review
* addressed linux peer review
* rename travisTest.sh to testApp.sh
* Update pom.xml
* Update pom.xml
* Update pom.xml
* Update pom.xml
* Update stopMinikube.sh
* SME review
* SME review
* fix hotspots
* fix hotspots
* fix hotspots
* fix hotspots
* SME review updates
* fixed test script
* fix tests
* user review updates
* PR checker fixes
* PR checker
* quoted command substitutions for PR checker
* added …
=> Merge qa to master: External server configuration (#117)
